import type { Metadata } from "next";
import { Lora, Roboto } from "next/font/google";
import { NotificationProvider } from "@/context/NotificationContext";
import Notification from "./components/Notification";
import "./globals.css";

// Import header styles here because importing in Header.tsx does not work for Server-side components
import "./components/Header.scss";

const lora = Lora({
	variable: "--font-lora",
	subsets: ["latin"],
});

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Blog | Q2 Interactive s.r.o.",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lora.variable} ${roboto.variable} antialiased`}>
				<NotificationProvider>
					<Notification />
					<div>{children}</div>
				</NotificationProvider>

				<footer className="w-full bg-[#343A40] text-[#E5E5E5] py-8 font-bold text-[14px]">
					<div className="inner-footer">
						<a
							className="hover:underline hover:underline-offset-4"
							href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
							target="_blank"
							rel="noopener noreferrer"
						>
							2025 | Q2 Interactive s.r.o.
						</a>
					</div>
				</footer>
			</body>
		</html>
	);
}
